server:
  port: 8080
  address: 127.0.0.1
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        same-site: strict

camel:
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true
  servlet:
    mapping:
      context-path: "/api/*"

dhis2:
  apiUrl: https://play.dhis2.org/dev/api
  username: admin
  password: district

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  health:
    show-details: always

spring:
  jmx:
    enabled: true
  security:
    user:
      roles: admin,viewer
#if(${artemis} == "Y")
  artemis:
    mode: EMBEDDED
    host: localhost
    port: 61616
    user: myuser
    password: mypass
#end

#if(${hawtio} == "Y")
hawtio:
  authenticationEnabled: false
#end

logging:
  file:
    name: ${artifactId}.log