name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.12.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - run: |
          mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
          -DarchetypeGroupId=org.hisp.dhis.integration.camel \
          -DarchetypeArtifactId=camel-archetype-dhis2 \
          -DgroupId=org.hisp.dhis.integration.camel \
          -Dhawtio=Y \
          -Ddatasonnet=Y \
          -Dfhir=Y \
          -Dartemis=Y \
          -DartifactId=my-camel-dhis2-app \
          -Dversion=1.0.0-SNAPSHOT && mvn package --file my-camel-dhis2-app/pom.xml
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          GPG_SECRET_KEYS: ${{ secrets.PGP_PRIVATE_KEY }}
        run: |
          echo -e "$GPG_SECRET_KEYS" | gpg --import --no-tty --batch --yes
          mvn deploy --settings .mvn/settings.xml -Dgpg.skip=false -Dmaven.test.skip=true -B
